version: '2'
services:

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - app-network

  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: php
    environment:
      - COMPOSER_MEMORY_LIMIT=-1
    ports:
      - "9000:9000"
    volumes:
      - ./src:/var/www
      - ./docker/php/php.override.ini:/usr/local/etc/php/conf.d/php.override.ini
    networks:
      - app-network

  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_DATA_DIR: ./docker/mongo/data/db
      MONGO_LOG_DIR: /dev/null
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
    command: mongod --logpath=/dev/null # --quiet
    volumes:
      - ./docker/mongo/data/db:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network

volumes:
  dbdata:
    driver: local

networks:
  app-network:
    driver: bridge
